// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/paif-arcade/HighStrikerSkillHit.tsx": () => import("../components/mockups/paif-arcade/HighStrikerSkillHit.tsx"),
  "./components/mockups/paif-arcade/LuckyBellReel.tsx": () => import("../components/mockups/paif-arcade/LuckyBellReel.tsx"),
  "./components/mockups/paif-arcade/PrizeRun.tsx": () => import("../components/mockups/paif-arcade/PrizeRun.tsx"),
  "./components/mockups/paif-arcade/RingToWinBallFlow.tsx": () => import("../components/mockups/paif-arcade/RingToWinBallFlow.tsx"),
  "./components/mockups/paif-high-striker/CarnivalSignalWall.tsx": () => import("../components/mockups/paif-high-striker/CarnivalSignalWall.tsx"),
  "./components/mockups/paif-high-striker/HighStrikerLanes.tsx": () => import("../components/mockups/paif-high-striker/HighStrikerLanes.tsx"),
  "./components/mockups/paif-invaders-vaults/PAIFInvadersVaults.tsx": () => import("../components/mockups/paif-invaders-vaults/PAIFInvadersVaults.tsx")
};
